version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NewsTW
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://viaduct.proxy.rlwy.net:59733/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ApMBTKJuIMfSYIUuYdHZTspZSWuouuTB
    ports:
      - '8080:8080'

volumes:
  postgres-data:
    driver: local