version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NewsTW
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '8080:8080'

  postgres:
    container_name: postgres-container
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

volumes:
  postgres-data:
    driver: local